### ISSUE TITLE
generating thumbnails from asset

### ISSUE THREAD

**Issue by ayon1911** [HHK1/PryntTrimmerView#18]
generating thumbnails fails pretty often

**Comment by HHK1** [comment]
hi @ayon1911, thanks for the feedback.
Could you provide more informations on what's going on exactly ? 
Do you have steps to reproduce ? 
Where are your assets located ? Are they local, remote ? 

Thank you

**Comment by ayon1911** [comment]
Hey tx dor replying back. Well i am recording some video clips and saving into the app document directory with an unique folder name. I access the directory and go through each video to trimm. I am using avplayer item as i have to do the video trimming one after another. 

The crash happens really randomly. I have a process of recording certain number of vedios and then trimming, merging and at last uploading to a ftp server. The problem occurs while fetching the assets for the first time and after recording all the videos. After the crash i launch the app and then the trimmerView can generate thumbnail. But after doing couple more time it crashes again. 

If u need more input then let me know. I would be happy to give u more feedback
