### ISSUE TITLE
Thumbnails not generated in trimmer view in iOS 11.4.1 

### ISSUE THREAD

**Issue by sanjukhunt** [HHK1/PryntTrimmerView#38]

**Comment by HHK1** [comment]
Is this related to https://github.com/HHK1/PryntTrimmerView/issues/18 ? 
I'll need more information in order to investigate on this.

**Comment by sanjukhunt** [comment]
May be not. 

I am using pod in my swift project. I set TrimerView in storyboard. But when assign asset. trimmer work perfectly but not showing any thumbnails in it. 

I am using this code 
![img_0917](https://user-images.githubusercontent.com/11293202/46796875-48b7cd00-cd6b-11e8-8415-98a6cb5c8ffc.jpg)

**Comment by HHK1** [comment]
Is your asset local or remote ? Does it work with the original example app ?

**Comment by sanjukhunt** [comment]
It's local. I pick video from camera roll. I didn't check with original example let me check it first.

**Comment by HHK1** [comment]
Check this one: https://github.com/HHK1/PryntTrimmerView/issues/30
It may be related to the size of your view not being defined, especially if you are using a storyboard.

**Comment by sanjukhunt** [comment]
Thank you. 

It's solved my problem. i set asset after complete the viewdidload and it's work.
