### ISSUE TITLE
Open up parent classes so that they can be extended outside this project

### ISSUE THREAD

**Issue by jraoatlogic** [HHK1/PryntTrimmerView#43]
Hi,

I'd like to extend or use AVAssetTimeSelector and AssetVideoScrollView outside this project, basically use them to write something similar to TrimmerView. Right now I couldn't do this because the classes are not open, and some properties are internal (such as assetPreview).

Thanks

**Comment by HHK1** [comment]
Hi,

I'm not sure about exposing the internals of the implementation inside the interface. What about forking this repo and creating your customised version of the TrimmerView ?
How much difference is there between what you're looking to make and the existing TrimmerView ?

**Comment by jraoatlogic** [comment]
Hi,

That's alright, I already implemented it by copying the files into my own project and renaming them, so it's not a hindrance, just want to see if there're better ways to do it, if opening the class is not an option it's fine to close this issue. I'm implementing a video timeline/scrubber, similar to the timeline in Apple's Photo app's video playback UI.

Thanks

**Comment by HHK1** [comment]
If you feel like this could be a nice addition to this Pod, feel free to open a PullRequest. Would be nice indeed to have a different UI option for this.
