### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [HHK1/PryntTrimmerView#44]
## Expected Results

No warning to convert PryntTrimmerView.framework to Swift 5

## Actual Results

Xcode created warnings to convert PryntTrimmerView.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by HHK1** [comment]
Fixed in #45, can you check it out and report any issues please ?

**Comment by HHK1** [comment]
Version 4.0.0 now supports Swift 5

**Comment by jlaws** [comment]
Thanks, works great
