### ISSUE TITLE
Visible white TrimmerView corners

### ISSUE THREAD

**Issue by CosmicVarion** [HHK1/PryntTrimmerView#48]
The TrimmerView corners are square whereas the start/end handle corners are rounded. So, with a non-white background and non-white handles, points of white are visible from the underlying bar at the corners of the handles.

**Comment by blurtime** [comment]
Here my small workaround:    
    let trimmerView: TrimmerView = {
        let trimmer = TrimmerView()

        trimmer.layer.cornerRadius = 3 //2 should actually suffice but there was still a tiny bit visible so I set it to 3
        trimmer.layer.masksToBounds = true
        
        return trimmer
    }()

**Comment by HHK1** [comment]
Solved, thanks @blurtime for your PR !
