### ISSUE TITLE
Can't set max duration

### ISSUE THREAD

**Issue by lbaomyscoopapp** [HHK1/PryntTrimmerView#58]
I tried to set max duration with 60 seconds. But i can trim video > max length. Min duration not correct also when try trim long video. 

```
trimmerView.minDuration = 3
trimmerView.maxDuration = 60
```

**Comment by arun-macrew** [comment]
@lbaomyscoopapp I'm getting same issue.

**Comment by lbaomyscoopapp** [comment]
@arun-macrew Have you fixed it.
