### ISSUE TITLE
Module compile error

### ISSUE THREAD

**Issue by Haibo-Zhou** [HHK1/PryntTrimmerView#62]
I get this error on latest Xcode 11.4.1 when using YPImagePicker, is there SWP available now?

Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.2 compiler: /Users/Chuck/Downloads/YPImagePicker-master/Carthage/Build/iOS/PryntTrimmerView.framework/Modules/PryntTrimmerView.swiftmodule/x86_64.swiftmodule

**Comment by HHK1** [comment]
This is an issue with the Carthage build ? You need a new version compiled with Swift 5.2.2 ?

**Comment by HHK1** [comment]
Added SPM support, does that solve your issue ?
