### ISSUE TITLE
Failed to install with Carthage

### ISSUE THREAD

**Issue by touyu** [HHK1/PryntTrimmerView#67]
```
github "HHK1/PryntTrimmerView" "master"
```

When I add this library with Carthage from the master branch, I get the following error when launching the app.

<img width="424" alt="スクリーンショット 2020-09-16 17 54 29" src="https://user-images.githubusercontent.com/12294921/93317251-35131c00-f848-11ea-8fa8-2d393823c3b9.png">

I suppose I should add Info.plist to the framework project (not for example project), what do you think?

For example, like [this pull request](https://github.com/HHK1/PryntTrimmerView/pull/68)

**Comment by HHK1** [comment]
Thanks for your PR, appreciate it. Can you confirm your issue is solved ?

**Comment by touyu** [comment]
Thank you for merging the PR. I close this issue.
