### ISSUE TITLE
Xcode 12 compatibility

### ISSUE THREAD

**Issue by nastasiupta** [HHK1/PryntTrimmerView#69]
Current pod version 4.0.0
Xcode version: 12.0 beta 6 (12A8189n)
The issue at build time:
file: ThumbSelectorView.swift 
line: 141
error: Cannot convert value of type 'CMTime' to type 'NSValue' in coercion

![Screenshot 2020-09-17 at 12 53 26](https://user-images.githubusercontent.com/13376064/93455304-da7bcd80-f8e4-11ea-8b14-c3355f498ebc.png)

**Comment by HHK1** [comment]
Fixed in 4.0.2
