### ISSUE TITLE
Xcode 12 issues 

### ISSUE THREAD

**Issue by petrykDima** [HHK1/PryntTrimmerView#71]
After update Xcode 12 there was problems with PryntTrimmer. It was updated to 4.0.2, but now I have new issue =( 
Could you please check it. 

<img width="271" alt="Screenshot 2020-09-18 at 10 45 40" src="https://user-images.githubusercontent.com/43542141/93570993-803e4380-f99c-11ea-8b4a-ccfa3855d981.png">

**Comment by parulgarg004** [comment]
@petrykDima I'm facing the same issue, can you please confirm how you fixed it?

**Comment by HHK1** [comment]
YPImagePicker needs to update their pod, this is not related to this library.
@s4cha @NikKovIos Do you have what you need from me ?

**Comment by NikKovIos** [comment]
@HHK1 No, thanks. Bug related to this is https://github.com/Yummypets/YPImagePicker/issues/569.
