### ISSUE TITLE
initialization method -init cannot be sent to an abstract object of class AVAsset: Create a concrete instance!

### ISSUE THREAD

**Issue by 08031992** [HHK1/PryntTrimmerView#72]
I have create a@IBOutlet  var selectThumbView: ThumbSelectorView! and navigate on view_controller using push navigation controller application crashes 
reason is initialization method -init cannot be sent to an abstract object of class AVAsset: Create a concrete instance!

**Comment by HHK1** [comment]
I need more context to understand your issue, could you provide a code example please ?

**Comment by NikKovIos** [comment]
Closed due to inactivity. Fill free to reopen.
