### ISSUE TITLE
How to trim the asset

### ISSUE THREAD

**Issue by coder123-star** [HHK1/PryntTrimmerView#73]
I have implemented this into my project, I am wondering how I can get the trimmed video. Is there a function or code that I need to add?

**Comment by HHK1** [comment]
Trimming of the assets is not provided by the library. The goal of this package is to give you UI controls, the implementation of actual trimming/cropping is up to you.

You can take a look at this thread for an example: https://stackoverflow.com/questions/35696188/how-to-trim-a-video-in-swift-for-a-particular-time

Or https://github.com/HHK1/PryntTrimmerView/blob/master/PryntTrimmerViewExample/VideoCropperViewController.swift for an example of cropping the video
