### ISSUE TITLE
Need support to set currently selected time rang

### ISSUE THREAD

**Issue by cp-satish-v** [HHK1/PryntTrimmerView#75]
set previously timed range on re-trim

**Comment by NikKovIos** [comment]
@cp-satish-v explain more detailed what do you offer please.

**Comment by cp-satish-v** [comment]
suppose i have video slip of 10 seconds, and i selected range of 5 to 10 seconds and save it to use later.
now i decided to update range, for that i need to display previously selected range. i think, currently that thing is not possible.

**Comment by NikKovIos** [comment]
@cp-satish-v 
https://github.com/HHK1/PryntTrimmerView/issues/76 is it the same you want?

**Comment by cp-satish-v** [comment]
Yes

**Comment by war3pc** [comment]
你答yes是什么鬼，根本没有解决哒
